name: Build DB

on:
  schedule:
  - cron:  "*/20 * * * *"
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        set -euo pipefail
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        python3 .github/build_db.py --push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
